

GET http://localhost:3001/api/persons


###
GET  http://localhost:3001/info


###
GET http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons/63d1dcc48c4f345eb4350500



###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "id": 0,
  "name": "1",
  "number": "1"
}

###
PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{
  "id": 1,
  "name": "Arto Hellas",
  "number": "1"
}

### 
DELETE http://localhost:3001/api/persons/63d1dcc48c4f345eb4350500